### PR TITLE
Separate CLI and lib

### LINKED ISSUE #48: split finch-rs into library and binary
Libraries [should not have a cargo.lock whereas binaries should](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries). The fact that finch-rs doesn't have a lockfile means that the `finch-rs` binary can't easily continue supporting a particular version of Rust without constantly running CI to verify that it compiles. A (possibly transitive) dependency could be updated at any time, breaking the build (this happened when I was working on #46). A lockfile prevents the build breaking at any time, but is ignored by libraries. The library version of finch-rs would need a minimum rust version of `stable`, since some of its dependencies require stable (for example [`object`](https://crates.io/crates/object)).

### PR DESCRIPTION
**Pull request by Keats**
Closes #48

### CODE REVIEW

**Review by GSGerritsen — APPROVED** [review]

**Comment by Keats** [comment]
cc @maxbla

**Comment by maxbla** [comment]
You did all the hard work, but the purpose of the split is to check in a lockfile for finch. Only that will allow you to have a minimum supported version older than stable.

**Comment by Keats** [comment]
Yep, I will check in the lockfile for the cli, thanks for catching that

**Comment by Keats** [comment]
It should be ok now.

**Pull request merged**
